### ISSUE TITLE
Add Pull Request tutorial to the README

### ISSUE THREAD

**Issue by Lorenzobattistela** [Ballerini-Server/Codefi#6]
As this project grows, a tutorial on how to create a good PR to standardize and make it easier for the maintainers. That said, i suggest adding a tutorial in the README after introducing the app and how to install it. This may include title, subject, images/videos, language and other things designed as required by the managers.

**Comment by danielsuguimoto** [comment]
Hey, people! Adding a PR template is a good idea, as well! https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by AlphaLawless** [comment]
Resolved!
